# Generated by Django 4.1 on 2022-08-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gender',
            new_name='moviegender',
        ),
    ]
