# Generated by Django 4.1.7 on 2024-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_movie_company_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_company',
            name='Movie_id',
        ),
        migrations.AlterField(
            model_name='movie_company',
            name='company_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
