# Generated by Django 4.1.7 on 2024-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_movie_company_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_company',
            name='company_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
