# Generated by Django 4.1.7 on 2024-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_movie_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_home',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slider', models.ImageField(blank=True, help_text='slider poster', upload_to='slider_poster')),
            ],
        ),
    ]
