# Generated by Django 4.1 on 2022-08-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('movie_id', models.IntegerField(help_text='Movie Id', primary_key=True, serialize=False)),
                ('movie_title', models.CharField(help_text='Movie Title', max_length=500)),
                ('movie_budget', models.IntegerField(help_text='Movie Budget')),
                ('movie_homepage', models.URLField(help_text='Movie Home Page')),
                ('movie_overview', models.CharField(help_text='Movie overview', max_length=500)),
                ('movie_votes_avg', models.DecimalField(decimal_places=2, help_text='Movie Budget', max_digits=2)),
                ('movie_votes_count', models.DecimalField(decimal_places=2, help_text='Movie Budget', max_digits=2)),
                ('movie_release_date', models.DateTimeField(help_text='Movie Budget')),
            ],
        ),
    ]
