# Generated by Django 4.1 on 2022-08-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_gender_moviegender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.AutoField(help_text='Movie Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moviegender',
            name='gender_id',
            field=models.AutoField(help_text='gender id', primary_key=True, serialize=False),
        ),
    ]
