# Generated by Django 4.1 on 2022-08-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_movie_movie_id_alter_moviegender_gender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='moviegender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moviegender'),
        ),
    ]
