# Generated by Django 4.1 on 2022-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='clint User Name', max_length=50)),
                ('emailaddress', models.EmailField(help_text='clinte Email Address', max_length=300)),
                ('name', models.CharField(help_text='Name', max_length=300)),
                ('mobile', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=50)),
                ('lastlogin', models.DateTimeField()),
                ('locations', models.CharField(max_length=60)),
                ('profileimage', models.ImageField(blank=True, upload_to='userprofile')),
                ('family', models.CharField(help_text='clint family name', max_length=300)),
                ('createdOn', models.DateTimeField()),
                ('updateOn', models.DateTimeField(default=None)),
                ('borndate', models.DateField()),
            ],
        ),
    ]
