# Generated by Django 4.1 on 2022-08-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='clint User Name', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_surce', models.ImageField(blank=True, upload_to='post_surce')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='username')),
            ],
        ),
    ]
